version: '3'
services:
  ipfs:
    image: ipfs/kubo:latest
    ports: ['5001:5001']

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    ports: ['9092:9092', '9644:9644']
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false

  postgres:
    image: postgres
    ports: ['5432:5432']
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --locale=C'
      POSTGRES_DB: graph-node
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in

  chain:
    build: {dockerfile: chain.dockerfile}
    ports: ['8545:8545']
    healthcheck:
      interval: 2s
      timeout: 2s
      retries: 10000
      test: |
        curl -sf localhost:8545 \
          -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
          | jq -rs '.[].result // "0x0"' \
          | (read input; [ "$$input" != '0x0' ])

  graph-node:
    depends_on: {chain: {condition: service_healthy}}
    image: graphprotocol/graph-node
    ports: ['8000:8000', '8001:8001', '8020:8020', '8030:8030', '8040:8040']
    environment:
      GRAPH_LOG: debug
      ipfs: 'http://ipfs:5001'
      ethereum: 'hardhat:http://chain:8545'
      postgres_db: graph-node
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      GRAPH_EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: synced
