# build the crate
build:
  cargo build
# run crate locally
dev CONFIG_PATH:
  cargo run {{CONFIG_PATH}}
# build crate locally with docker
docker_build IMAGE:
  DOCKER_BUILDKIT=1 docker build . -t {{IMAGE}}
# run the docker image locally with docker compose
docker_up:
  docker compose up -d
# creates the topic in the kafka instance
create_topic:
  docker exec -it redpanda_1 rpk topic create gateway_subscription_query_results --brokers=localhost:9092
# teardown the docker image
docker_down:
  docker compose down
# clean any hanging docker volumes
docker_clean:
  docker system prune --volumes
# teardown the docker image and clean any hanging docker volumes
docker_down_clean: docker_down
  docker system prune --volumes