apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-subscriptions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-subscriptions-api
  template:
    metadata:
      labels:
        app: graph-subscriptions-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9090'
    spec:
      imagePullSecrets:
        - name: docker-registry
      volumes:
        - name: subscriptions-kafka-logs-certs
          configMap:
            name: subscriptions-kafka-logs-certs
      containers:
        - name: app
          image: graph-subscriptions-api
          command:
            - /opt/graph-subscriptions-api/target/release/graph-subscriptions-api
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              port: metrics
              path: /metrics
          resources:
            limits:
              memory: 1Gi
              cpu: '1'
            requests:
              memory: 512Mi
              cpu: '0.5'
          volumeMounts:
            - name: subscriptions-kafka-logs-certs
              mountPath: /opt/redpanda_config/ca.crt
              subPath: ca.crt
            - name: subscriptions-kafka-logs-certs
              mountPath: /opt/redpanda_config/client.crt
              subPath: client.crt
            - name: subscriptions-kafka-logs-certs
              mountPath: /opt/redpanda_config/client.key
              subPath: client.key
          envFrom:
            - configMapRef: # this contains general environment config plaintext values
                name: graph-subscriptions-api-env
            - secretRef:
                # contains the kafka connection params stored as an encrypted secrets
                ## GRAPH_SUBSCRIPTION_LOGS_KAFKA_BROKER
                ## GRAPH_SUBSCRIPTION_LOGS_KAFKA_GROUP_ID
                ## GRAPH_SUBSCRIPTION_LOGS_KAFKA_TOPIC_ID
                ## GRAPH_SUBSCRIPTION_LOGS_KAFKA_SASL_USERNAME
                ## GRAPH_SUBSCRIPTION_LOGS_KAFKA_SASL_PASSWORD
                name: graph-subscriptions-api-kafka-env
          env:
            # parse the db secrets. use to build the exposed GRAPH_SUBSCRIPTION_LOGS_DB_URL the app uses
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: graph-subscriptions-api-db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: graph-subscriptions-api-db-env
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: graph-subscriptions-api-db-env
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graph-subscriptions-api-db-env
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: graph-subscriptions-api-db-env
                  key: DB_NAME
            - name: GRAPH_SUBSCRIPTION_LOGS_DB_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?schema=public&connect_timeout=300
            # parse out the kafka security config & SSL/CA file locations
            - name: GRAPH_SUBSCRIPTION_LOGS_KAFKA_SECURITY_PROTOCOL
              value: sasl_ssl
            - name: GRAPH_SUBSCRIPTION_LOGS_KAFKA_SASL_MECHANISM
              value: SCRAM-SHA-256
            - name: GRAPH_SUBSCRIPTION_LOGS_KAFKA_SSL_CA_LOC
              value: /opt/redpanda_config/ca.crt
            - name: GRAPH_SUBSCRIPTION_LOGS_KAFKA_SSL_CERT_LOC
              value: /opt/redpanda_config/client.crt
            - name: GRAPH_SUBSCRIPTION_LOGS_KAFKA_SSL_KEY_LOC
              value: /opt/redpanda_config/client.key
---
apiVersion: v1
kind: Service
metadata:
  name: graph-subscriptions-api
spec:
  type: ClusterIP
  selector:
    app: graph-subscriptions-api
  ports:
    - name: http
      port: 4000
      protocol: TCP
    - name: metrics
      port: 9090
      protocol: TCP
