export const USER_SUBSCRIPTION_EVENT_TYPE__CREATED = 'CREATED';
export const USER_SUBSCRIPTION_EVENT_TYPE__CANCELED = 'CANCELED';
export const USER_SUBSCRIPTION_EVENT_TYPE__RENEW = 'RENEW';
export const USER_SUBSCRIPTION_EVENT_TYPE__UPGRADE = 'UPGRADE';
export const USER_SUBSCRIPTION_EVENT_TYPE__DOWNGRADE = 'DOWNGRADE';
