on:
  push:
    branches: ['**']

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-subgraph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
        working-directory: subgraph
      - run: yarn test
        working-directory: subgraph
  test_graph-subscriptions-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
        working-directory: graph-subscriptions-api
